/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { Link } from 'react-router-dom';
import ServiceGrid from "./ServiceGrid";

import FAQSection from "../faq/FAQSection";
import BookASpot from "./BookASpot";

const ServicesPage = () => {
  

  return (
    <div className="bg-[#f0f8ff] min-h-screen">
      <section className="hero bg-cover bg-center h-96 " style={{ backgroundImage: "url('/images/7777.png')" }}>
      <div className="bg-black bg-opacity-50 h-full flex flex-col items-center justify-center">
        <h1 className="text-4xl font-bold text-center text-gray-200 mb-4">Services</h1>
        <p className="text-xl italic text-center text-gray-200">
          Comprehensive Pet Care Services Tailored to Your Pets Needs
        </p>
      </div>
    
      </section>

      {/* <ServiceCategories /> */}

      <ServiceGrid  />
      <BookASpot />
      <FAQSection />

    

      <div className="fixed bottom-0 left-0 right-0 bg-white shadow-lg p-4 flex  justify-center space-x-4">
        <Link to="/booking-form">
        <button className="bg-[#40bfe0] text-gray-800 px-6 py-2 rounded-full hover:bg-[#1e778e] hover:text-gray-100 transition duration-300">
          Book Now
        </button>
        </Link>

        <Link to="/contact">
        <button className="bg-gray-800 text-white px-6 py-2 rounded-full hover:bg-[#1e778e] hover:text-gray-100 transition duration-300">
          Contact
        </button>
        </Link>
      </div>
    </div>
  );
};

export default ServicesPage;
