/**
 * This code was generated by Builder.io.
 */
import React from "react";

const categories = [
  "Dog Walking",
  "Pet Sitting",
  "Grooming",
  "Training",
  "Pet Transportation",
  "Specialized Care",
];

const ServiceCategories = () => {
  return (
    <nav className="bg-gray-800 p-4">
      <ul className="flex flex-wrap justify-center space-x-4">
        {categories.map((category) => (
          <li key={category}>
            <a
              href={`#${category.toLowerCase().replace(" ", "-")}`}
              className="text-white hover:text-gray-300 transition duration-300"
            >
              {category}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default ServiceCategories;
