/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OurJourney = () => {
  return (
    <section className="py-16 bg-[#f0f8ff]">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">The Journey</h2>
        <p className="text-xl text-center max-w-3xl mx-auto">
          The story began with a love for animals and 
          a vision to create a place where pets receive the utmost care and affection. 
          From humble beginnings to becoming a trusted pet care provider, 
          the journey is marked by a commitment to excellence and love for animals.
        </p>
      </div>
    </section>
  );
};

export default OurJourney;
