/**
 * This code was generated by Builder.io.
 */
import React from "react";

const teamMembers = [
  
  {
    name: "Pamela Marbett",
    role: "Founder & Head Pet Carer",
    image: "/images/8.png",
  },
];

const TeamSection = () => {
  return (
    <section className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl font-bold text-center mb-8">Meet the Team</h2>
        <p className="text-xl text-center max-w-3xl mx-auto mb-12">
          Meet Pamela Marbett, the owner of Pamela’s Pampered Pets in Seattle, Washington. With over 20 years of experience, Pamela provides licensed, insured, and CPR/First Aid certified pet care. 
        </p>
        <p className="text-xl text-center max-w-3xl mx-auto mb-12">
           Services include daily walks, special needs care, pet sitting, and overnight stays. Each pet receives personalized attention and care. Book a spot today!
        </p>
        <div className="flex flex-col items-center ">
          {teamMembers.map((member, index) => (
            <div
              key={index}
              className="bg-[#f0f8ff] rounded-lg shadow-md overflow-hidden"
            >
              <img
                src={member.image}
                alt={member.name}
                className="w-full h-64 object-cover"
              />
              <div className="p-6">
                <h3 className="text-xl font-bold mb-2">{member.name}</h3>
                <p className="text-gray-600">{member.role}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default TeamSection;
