/**
 * This code was generated by Builder.io.
 */

import React, { useState } from "react";

import Tab from "./Tab";
import VideoPlayer from "./VideoPlayer";
import VideoThumbnail from "./VideoThumbnail";
import PhotoThumbnail from "./PhotoThumbnail";
import Testimonial from "./Testimonial";
import Modal from "./Modal";
// import teachingdogstoswimwebm from '/videos/teachingdogstoswimwebm.mp4'
import fullherovideo from '/videos/fullherovideo.mp4';
import teachingdogstoswimwebmposter from '/images/teachingdogstoswimwebmposter.png'
import { PlayIcon, CameraIcon } from "@heroicons/react/solid";

const OurWorkInAction = () => {
  const [activeTab, setActiveTab] = useState("videos");
  const [modalContent, setModalContent] = useState(null);

  const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 10000,
  };

 const videos = [
    {
      id: 1,
      src: '/videos/doggievideo.mp4',
      title: "Comfort and Care on the Go - Pamela’s Pampered Pets",
      description: " Experience the warmth and attention we provide your furr family. Watch as two adorable dogs, clad in stylish red sweaters, enjoy a cozy ride in the backseat of a vehicle. The scene captures the essence of our pet care services in Seattle, Washington – ensuring every pet feels loved and pampered even while traveling. It’s not just about getting from A to B; it’s about doing so with comfort, safety, and a touch of luxury for your furry friends.",
      poster: '/images/doggievideoposter.png'
    },
    {
      id: 2,
      src: '/videos/dogbathingg.mp4', // Ensure this path is correct
      title: "Pampered Pooch Bath Time",
      description: "Watch as one of our adorable dogs enjoys a soothing bath. Our professional and caring team ensures that every pet receives gentle and thorough grooming, making bath time a relaxing experience. Discover how we prioritize the comfort and happiness of your furry friends with our top-notch pet care services.P ",
      poster:'/images/dogbathing.gif'
    },
    {
      id: 3,
      src: '/videos/conure.mp4',
      title: "Jo's Playtime.",
      description: "Experience a delightful moment from Pamela's Pampered Pets Care Services in Seattle, Washington, where our expert team ensures that every pet, including this charming parrot, receives the best care and attention. Watch as our playful parrot enjoys a lively and engaging environment, showcasing the loving and professional care we provide to all our feathered and furry friends.",
      poster: '/images/conure.gif'
      
    },
    
    {
      id: 4,
      src: '/videos/doggyicecreamm.mp4',
      title: "Doggy Delight: Ice Cream Treat Time",
      description: "Join us for a special moment of joy as one of our adorable dogs enjoys a delicious ice cream treat. Our dedicated team ensures that every pet experiences fun, love, and top-notch care. Watch this delightful scene and see why our pet care services are a cut above the rest.",
      poster: '/images/doggyicecream.gif'
      
    },
    {
      id: 5,
      src: '/videos/bird.mp4',
      title: "Jo's Playtime.",
      description: "Experience a delightful moment from Pamela's Pampered Pets Care Services in Seattle, Washington, where our expert team ensures that every pet, including this charming parrot, receives the best care and attention. Watch as our playful parrot enjoys a lively and engaging environment, showcasing the loving and professional care we provide to all our feathered and furry friends.",
      poster: '/images/birdposter.gif'
      
    },
    {
      id: 6,
      src: '/videos/happydog.webm',
      title: "Playful Pooches at Pamela’s Pampered Pets",
      description: "Dive into the delightful world of canine care with our video from Pamela’s Pampered Pets in Seattle, Washington. Witness the joy and energy of a black and white dog as it enjoys playtime in a spacious, fenced outdoor area. This engaging footage showcases the attentive services provided, ensuring each pet experiences fun, exercise, and socialization in a safe environment",
      poster: '/images/happydoggif.gif'  
      
    },
    {
      id: 7,
      src: '/videos/teachingdogstoswim1.mp4',
      title: "Seaside Serenity at Pamela’s Pampered Pets",
      description: "Experience the tranquility of Seattle’s scenic beauty with Pamela’s Pampered Pets. This video captures a serene moment as a well-cared-for dog enjoys a sunny day out on a driftwood log by the calm waters of Puget Sound. With the city’s skyline in the distance, this pet is the epitome of relaxation and contentment under our attentive care. Join us for an adventure where your pet’s happiness is our priority.",
      poster: '/images/dogonlogofwood.gif'  
      
    },
    {
      id: 8,
      src: '/videos/acrobaticdoggy.mp4',
      title: "Companionship in Every Step: A Day at Pamela’s Pampered Pets Care Services",
      description: "Experience the warmth and dedication of Pamela’s Pampered Pets Care Services with this heartwarming video. Set against the lush greenery of Seattle, Washington, the video showcases a delightful moment between two furry friends under our care. Watch as a golden-coated dog and a fluffy white companion enjoy a playful encounter during their walk, exemplifying the joy and socialization we provide for every pet. It’s not just a service; it’s where pets find happiness and companionship in their daily routines.",
      poster: '/images/acrobaticdoggy.gif'  
      
    },
    
    {
      id: 9,
      src: '/videos/parrot.mp4',
      title: "Feathered Companionship at Pamela’s Pampered Pets",
      description: "Dive into the world of avian care with Pamela’s Pampered Pets, based in Seattle, Washington. This engaging video showcases the personalized and attentive services provided to a vibrant green parrot, highlighting the trust and comfort that Pamela’s team builds with every pet in their care. Experience the warmth and expertise that make Pamela’s Pampered Pets a haven for your feathered friends.",
      poster: '/images/parrot.png'  
      
    },
    {
      id: 10,
      src: '/videos/dogshowling.mp4',
      title: "Feathered Companionship at Pamela’s Pampered Pets",
      description: "Dive into the world of avian care with Pamela’s Pampered Pets, based in Seattle, Washington. This engaging video showcases the personalized and attentive services provided to a vibrant green parrot, highlighting the trust and comfort that Pamela’s team builds with every pet in their care. Experience the warmth and expertise that make Pamela’s Pampered Pets a haven for your feathered friends.",
      poster: '/images/dogshowling.gif'  
      
    },
  ];

  const photos = [
    {
      id: 1,
      src: "/images/7777.png",
      title: "Compassionate Canine Care at Pamela’s Pampered Pets",
      description: "Experience the pinnacle of pet pampering with Seattle’s own Pamela’s Pampered Pets – Where every animal is treated like family",
      alt:"A well-groomed, robust dog wearing a cozy striped sweater stands on lush green grass, showcasing the attentive and personalized care provided by Pamela’s Pampered Pets in Seattle"
    },
    {
      id: 2,
      src: "/images/144.png",
      title: "Two Dogs Relaxing Comfortably on Cozy Bed",
      description: "A Peaceful moment of two dogs relaxing indoors, highlighting the comfort and companionship pets bring to a home. ",
      subtext:"This image showcases a peaceful moment of two dogs relaxing indoors, highlighting the comfort and companionship pets bring to a home. Ideal for content related to pet care, home decor for pet owners, or the joys of having pets.Two dogs are lying on cushioned beds in a cozy indoor setting. The brown dog on the left rests on a beige cushion with its tongue out, appearing content. The grey dog on the right is lying on a colorful blanket featuring various dog silhouettes, looking directly at the camera. Surrounding them are soft furniture and a calm ambiance.",
      alt:"Two contented dogs lounging comfortably indoors at Pamela’s Pampered Pets, a pet care facility in Seattle. One dog is resting on a beige cushion with its tongue playfully out, while the other lies on a colorful blanket with bone and paw print patterns, symbolizing the attentive and personalized care they receive.",
    },
    {
      id: 3,
      src: "/images/155.png",
      title: "Cozy Afternoon Retreat",
      description: " A well-cared-for pet enjoying a cozy moment. Quality pet care services available in Seattle.",
      alt:"A cute dog with a red blanket wrapped around its head, looking up with a gentle expression, receiving care at Pamela's Pampered Pets in Seattle, WA."
    },
    {
      id: 4,
      src: "/images/14four.png",
      title: "Companions in Stripes: A Canine Duo’s Portrait",
      description: "Two dogs in striped outfits share a moment of camaraderie on a cozy carpet.",
      subtext:"The image captures the bond between two pet dogs, dressed in matching striped attire, highlighting their human-like companionship and the trend of pet fashion.",
      alt:"Two dogs wearing striped shirts sitting on a carpet, one facing away and one looking at the camera.",
    },
    {
      id: 5,
      src: "/images/doggievideoposter.png",
      title: "Canine Co-Pilots: Ready for the Road",
      description: "Two dogs in red outfits eagerly look out the car window, ready for their next adventure.",
      subtext:"These two canine companions, dressed in vibrant red, add a touch of whimsy and warmth to any road trip, showcasing the bond between pets and their owners during travel.",
      alt:"Two dogs in red shirts on a car’s back seat looking out the window.",
    },
     {
      id: 6,
      src: "/images/picturetwo.png",
      title: "Cozy Canine Comfort ",
      description: "A dachshund peeks out from under a plush purple blanket, exuding warmth and relaxation",
      subtext:"The picture capures a moment of contentment, showcasing the simple joy pets find in everyday comforts. It may resonate with viewers who appreciate the companionship and endearing quirks of their furry friends.",
      alt:"A dog under a purple blanket on a chair.",
    },
    {
      id: 7,
      src: "/images/pictureone.png",
      title: "Pensive Pooch: A Moment of Reflection",
      description: "A black and white dog gazes thoughtfully, cradling its chin in a paw",
      subtext:"This image captures a candid moment of a pet that appears to be deep in thought, highlighting the often human-like expressions animals can exhibit.",
      alt:"Black and white dog resting its chin on its paw, looking contemplative.",
    },
    {
      id: 8,
      src: "/images/122.png",
      title: "Curious Canine Companion",
      description: "A watchful dog with striking eyes stands attentively indoors, exuding a mix of alertness and friendliness.",
      subtext:"This image captures the essence of domestic canine companionship, showcasing a dog’s inquisitive nature within the comfort of a home setting. The dog’s attentive gaze suggests a moment of interaction or anticipation.",
      alt:"Dog with distinct markings stands inside a home, looking up expectantly.",
    },
    {
      id: 9,
      src: "/images/11.gif",
      title: "A Pup’s Inquisitive Gaze",
      description: "A black and white dog with a curious expression sits inside a cozy room, surrounded by furniture and books",
      subtext:"This image captures the essence of domestic pet life, highlighting the inquisitive nature of a dog within the familiar confines of its home environment",
      alt:"Dog with a quizzical look in a home setting.",
    },
     {
      id: 10,
      src: "./images/longhappydoggiff.gif",
      title: "A Pup’s Inquisitive Gaze",
      description: "A black and white dog with a curious expression sits inside a cozy room, surrounded by furniture and books",
      subtext:"This image captures the essence of domestic pet life, highlighting the inquisitive nature of a dog within the familiar confines of its home environment",
      alt:"Dog with a quizzical look in a home setting.",
    },
  
  ];

  const testimonials = [
  {
    "quote": "We adopted our dear Winston in September 2020. We met Pam Marbett in May 2021 and wish we had done so sooner. Pam is a dog parent’s dream. She dog sat, house sat, and walked Winston for much of 2021. Pam also cared for my parent’s 13-year-old dog during our family vacations. She was incredibly attentive, loving, and professional with both dogs. Pam's rapport with the pets was amazing.",
    "author": "Melissa B",
    "image": "/images/aboutimage.png",
    "id": "a0ce1"
  },
  {
    "quote": "Pam was punctual, flexible, reliable, communicative, and fully focused on our dogs. Since moving abroad, we dearly miss Pam’s expert care and highly recommend her. We often talk about how much we miss her and her care for Winston. Pam frequently drove Winston from West Seattle to his favorite off-leash park in Marymoor, spoiling him with specialty treats. She also helped with vet appointments as part of moving Winston internationally. Pam went above and beyond, and we cannot recommend her highly enough!",
    "author": "Melissa B",
    "image": "/images/aboutimage.png",
    "id": "a0ce2"
  },
  {
    "quote":"Pam has cared for our large mixed breed dog on several occasions, and we couldn’t be happier or trust her more. She is very empathetic and fully commits to her role in keeping our pup safe and happy while his humans are away. In fact, on her last visit, I had to ask just what she had been doing daily, because our typically very anxious and reactive dog was the most relaxed we’d ever seen him! Pam is an expert communicator and works hard to ensure our instructions are followed to the letter. You and your pets will be lucky to work with her!",
    "author": "Susan",
    "image": "/images/aboutimage.png",
    "id": "aec01"
  },
  {
    "quote": "Pam is the Mary Poppins of dog sitting! She loves on what she does and takes caring for my dogs very seriously. I don’t think they miss me at all when I’m gone. It is so comforting to know they are being cared for by Pam and I can’t say how much I appreciate her!",
    "author": "Anonymous",
    "image": "/images/aboutimage.png",
    "id": "e9cf"
  },
  {
    "quote": "Pam recently looked after our 2 dogs (including one very elderly dog) and our blue crowned conure. Communication was excellent at all stages. She sent frequent updates, took our young dog on many outings and spoiled them rotten. Our plants were all alive and thriving when we got home and our house was spotless. Cannot recommend Pam highly enough!",
    "author": "Anonymous",
    "image": "/images/aboutimage.png",
    "id": "a729"
  }
];
const slides = [
    { src: "/images/longhappydoggiff.gif", caption: "Happy Moment 1" }
   
  ];
  const openModal = (content) => {
    setModalContent(content);
  };

  const closeModal = () => {
    setModalContent(null);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-center mb-2">
        Our Work in Action
      </h1>
      <p className="text-xl text-center text-gray-600 mb-8">
        See the joy and care we bring to pets and their owners.
      </p>

      <div className="flex justify-center mb-8">
        <Tab
          icon={<PlayIcon className="w-5 h-5 " />}
          label="Videos"
          isActive={activeTab === "videos"}
          onClick={() => setActiveTab("videos")}
        />
        <Tab
          icon={<CameraIcon className="w-5 h-5" />}
          label="Photos"
          isActive={activeTab === "photos"}
          onClick={() => setActiveTab("photos")}
        />
      </div>

      {activeTab === "videos" && (
        <div className=''>
          <div className="mb-8">
            <VideoPlayer autoPlay loop muted src={fullherovideo} poster={teachingdogstoswimwebmposter} />
          
            <div className=" flex items-center justify-center">
              <h2 className="text-3xl font-bold text-gray-800 bg-[#b2dbff] bg-opacity-50 p-4 rounded">
                Watch our furry friends in action!
              </h2>
            </div>

          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3  gap-8">
            {videos.map((video) => (
              <VideoThumbnail
                key={video.id}
                src={video.poster}
                title={video.title}
                description={video.description}
                onClick={() =>
                  openModal(
                    <div>
                      <VideoPlayer src={video.src} />
                      <h3 className="text-2xl font-bold mt-4">{video.title}</h3>
                      <p className="text-gray-600">{video.description}</p>
                    </div>
                  )
                }
              />
            ))}
          </div>
        </div>
      )}

      {activeTab === "photos" && (
        <div>
          {/* <div className="relative  mb-8">
            <img
              src="/images/happydoggif.gif"
              alt="Hero"
              className="w-96 h-96 mx-auto rounded-lg"
            />
            <div className="absolute inset-0 flex items-center justify-center">
              <h2 className="text-3xl font-bold text-white bg-black bg-opacity-50 p-4 rounded">
                Moments of Happiness
              </h2>
            </div>
          </div> */}
      <div className="relative mb-8">
      

      <div className="w-full mt-8">
        
          
            <div key='one' className="relative text-center">
              
              <img src='./images/longesthappydoggiff.gif'  className="w-auto h-full object-cover rounded-xl mx-auto" />
              <div className="w-96 h-96 object-cover mx-auto absolute inset-0 flex items-end justify-center rounded-xl bg-black bg-opacity-50">
               
                <h2 className="text-3xl text-center font-bold text-white bg-black rounded-xl bg-opacity-50 p-4 ">
                  Captured Moments of Happiness
                </h2>
              </div>
            </div>
          
      
      </div>
    </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {photos.map((photo) => (
              <PhotoThumbnail
                key={photo.id}
                src={photo.src}
                title={photo.title}
                description={photo.description}
                onClick={() =>
                  openModal(
                    <div>
                      <img
                        src={photo.src}
                        alt={photo.title}
                        className="w-full rounded-lg"
                      />
                      <h3 className="text-2xl font-bold mt-4">{photo.title}</h3>
                      <p className="text-gray-600">{photo.description}</p>
                    </div>
                  )
                }
              />
            ))}
          </div>
        </div>
      )}
      
      

      <Modal isOpen={!!modalContent} onClose={closeModal}>
        {modalContent}
      </Modal>
    </div>
  );
};

export default OurWorkInAction;
