/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PhotoThumbnail = ({ src, title, description, onClick }) => (
  <div className="cursor-pointer group" onClick={onClick}>
    <img
      src={src}
      alt={title}
      className="w-full h-48 object-cover rounded-lg transition-transform group-hover:scale-105"
    />
    <h3 className="mt-2 text-lg font-semibold">{title}</h3>
    <p className="text-sm text-gray-600">{description}</p>
  </div>
);

export default PhotoThumbnail;
