/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Tab = ({ icon, label, isActive, onClick }) => (
  <button
    className={`flex items-center px-4 py-2 rounded-t-lg transition-colors ${
      isActive
        ? "bg-[#40bfe0] text-white"
        : "bg-gray-800 text-gray-200 hover:bg-gray-600"
    }`}
    onClick={onClick}
  >
    {icon}
    <span className="ml-2">{label}</span>
  </button>
);

export default Tab;
