/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Slider from 'react-slick';



const testimonials = [
  {
    "quote": "We adopted our dear Winston in September 2020. We met Pam Marbett in May 2021 and wish we had done so sooner. Pam is a dog parent’s dream. She dog sat, house sat, and walked Winston for much of 2021. Pam also cared for my parent’s 13-year-old dog during our family vacations. She was incredibly attentive, loving, and professional with both dogs. Pam's rapport with the pets was amazing.",
    "author": "Melissa B",
    "image": "/images/122.png",
    "id": "a0ce1"
  },
  {
    "quote":"Pam has cared for our large mixed breed dog on several occasions, and we couldn’t be happier or trust her more. She is very empathetic and fully commits to her role in keeping our pup safe and happy while his humans are away. In fact, on her last visit, I had to ask just what she had been doing daily, because our typically very anxious and reactive dog was the most relaxed we’d ever seen him! Pam is an expert communicator and works hard to ensure our instructions are followed to the letter. You and your pets will be lucky to work with her!",
    "author": "Susan",
    "image": "/images/111.png",
    "id": "aec01"
  },
  {
    "quote": "Pam was punctual, flexible, reliable, communicative, and fully focused on our dogs. Since moving abroad, we dearly miss Pam’s expert care and highly recommend her. We often talk about how much we miss her and her care for Winston. Pam frequently drove Winston from West Seattle to his favorite off-leash park in Marymoor, spoiling him with specialty treats. She also helped with vet appointments as part of moving Winston internationally. Pam went above and beyond, and we cannot recommend her highly enough!",
    "author": "Melissa B",
    "image": "/images/77.png",
    "id": "a0ce2"
  },
  {
    "quote": "Pam is the Mary Poppins of dog sitting! She loves on what she does and takes caring for my dogs very seriously. I don’t think they miss me at all when I’m gone. It is so comforting to know they are being cared for by Pam and I can’t say how much I appreciate her!",
    "author": "Anonymous",
    "image": "/images/155.png",
    "id": "e9cf"
  },
  {
    "quote": "Pam recently looked after our 2 dogs (including one very elderly dog) and our blue crowned conure. Communication was excellent at all stages. She sent frequent updates, took our young dog on many outings and spoiled them rotten. Our plants were all alive and thriving when we got home and our house was spotless. Cannot recommend Pam highly enough!",
    "author": "Anonymous",
    "image": "/images/14four.png",
    "id": "a729"
  }
];

const sliderSettings = {
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 5000,
  };
const Testimonial = () => (
  <section className="relative bg-[#f0f8ff] py-8">
  <div className="absolute top-0 left-0 w-full h-full bg-cover blur-sm rounded-full bg-center opacity-50" style={{ backgroundImage: "url('/images/pawfulheart.png')" }}></div>
  <header className="text-3xl font-bold relative z-10 text-center mb-8  text-gray-900 dark:text-gray-100">
    What Others Are Saying About Pamela
  </header>
  <Slider {...sliderSettings} className="relative  z-10 mx-auto max-w-3xl">
    {testimonials.map(testimonial => (
      <div key={testimonial.id} className="mx-auto w-full sm:w-4/5 lg:w-3/5 bg-white bg-opacity-50 p-8 rounded-lg text-center italic">
        <img src={testimonial.image} alt={testimonial.author} className="mx-auto mb-4 rounded-full w-24 h-24 object-cover" />
        <blockquote className="mb-4 text-gray-800">
          <p className="lg:text-xl sm:text-lg font-roboto-mono text-lg">{testimonial.quote}</p>
          <footer className="text-lg font-semibold text-gray-600">— {testimonial.author}</footer>
        </blockquote>
      </div>
    ))}
  </Slider>
</section>
);

export default Testimonial;
