/**
 * This code was generated by Builder.io.
 */
import React from "react";

const VideoPlayer = ({ src, poster }) => (
  <div className="relative w-full aspect-video">
    <video className="w-full h-full object-cover" controls poster={poster}>
      <source src={src} type="video/mp4" />
      Your browser does not support the video tag.
    </video>
  </div>
);

export default VideoPlayer;
